apiVersion: v1
kind: ConfigMap
metadata:
  name: shopverse-config
  labels:
    app: shopverse
data:
  DB_SECRET_ARN: {{ .Values.rds.secretArn | quote }}
  DB_SSLMODE: "require"
  AWS_REGION: {{ .Values.aws.region | quote }}
  FRONTEND_ORIGIN: "*"
