apiVersion: v1
kind: ServiceAccount

metadata:
  name: shopverse-backend

  namespace: {{ .Release.Namespace }}

  labels:
    app: shopverse
    component: backend

  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.backend.iamRoleArn | quote }}
    
