apiVersion: v1
kind: ServiceAccount
metadata:
  name: shopverse-backend
  labels:
    app: shopverse
    component: backend
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.backend.irsaRoleArn | quote }}
